[metadata]
name = quotez
version = 1.0.0
description = Quotez app
long_description = file: README.md
long_description_content_type = text/markdown
author = QuoteZProject
license = MIT

[options]
packages = find:
py_modules = main
include_package_data = True
zip_safe = False

[options.packages.find]
where = .

[options.entry_points]
console_scripts =
    quotez = main:main
